/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;

import Conectar.Conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class Buscar extends javax.swing.JDialog {

    Conectar cc= new Conectar();
    Connection cn= cc.conexion();
    DefaultTableModel modelo;
    String tipoBusqueda;
    
    
    public Buscar(String tipoBusqueda) {
      
        initComponents();
        this.tipoBusqueda =tipoBusqueda;
        tabla.add(mnTabla);
    }

    public void BuscarCliente(){
        String[]titulos={"Codigo","Nombres","Apellidos","Sexo","C.I."} ;  
        String []Registros= new String[5];
        modelo=new DefaultTableModel(null,titulos);
        String Sql="SELECT idCliente,nombreCliente,apellidoCliente,ciCliente FROM Cliente WHERE CONCAT(idCliente,nombreCliente,apellidoCliente,ciCliente) LIKE '%"+jtBuscar+"%'";
        Statement st;
        try {
            st = cn.createStatement();
        
            ResultSet rs = st.executeQuery(Sql);
            
            while(rs.next())
             {
                 System.out.print("encontrar");
                 Registros[0]=rs.getString(0);  
                 Registros[1]=rs.getString(1);  
                 Registros[2]=rs.getString(2);  
                 Registros[3]=rs.getString(3);  
                 Registros[4]=rs.getString(4);  
                 
                 modelo.addRow(Registros);
             } 
            tabla.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    
    }
    public void tabla(){
        if(tipoBusqueda.equals("Cliente")){
            
        }
        if(tipoBusqueda.equals("Empleado")){
            
        }
        if(tipoBusqueda.equals("Auto")){
        
        
        }
        
    }
    
    int id=-1;
    public int getId(){
         
        return id;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnTabla = new javax.swing.JMenu();
        mnModificar = new javax.swing.JMenuItem();
        lBuscar = new javax.swing.JLabel();
        jtBuscar = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        mnTabla.setText("jMenu2");

        mnModificar.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lBuscar.setText("Buscar");

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(bBuscar)
                        .addGap(27, 27, 27)
                        .addComponent(bCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBuscar)
                    .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar)
                    .addComponent(bCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        tabla();
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtBuscar;
    private javax.swing.JLabel lBuscar;
    private javax.swing.JMenuItem mnModificar;
    private javax.swing.JMenu mnTabla;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
