/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;

import Conectar.Conectar;
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * 
 */
public class RegistrarCliente extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarEmpleado
     */
    
    //JDateChooser fechaReg;
    
    Conectar cc= new Conectar();
    Connection cn= cc.conexion();
    
    private byte[] f=null;
    public RegistrarCliente() throws FileNotFoundException {
        initComponents();
        Calendar c2 = new GregorianCalendar();
        fechaRegistro.setCalendar(c2);
        File fichero = new java.io.File("/imagen/user4.png"); 
        FileInputStream ficheroStream = new FileInputStream(fichero); 
        f = new byte[(int)fichero.length()]; 
          
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTabla = new javax.swing.JMenu();
        menuModificar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        PanelSuperior = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        bGuardar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        PanelImagen = new javax.swing.JPanel();
        jImagen = new javax.swing.JLabel();
        PanelFormulario = new javax.swing.JPanel();
        lNombre = new javax.swing.JLabel();
        lApellido = new javax.swing.JLabel();
        lsexo = new javax.swing.JLabel();
        lDireccion = new javax.swing.JLabel();
        lci = new javax.swing.JLabel();
        lTelefono = new javax.swing.JLabel();
        lFecha = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jCombSexo = new javax.swing.JComboBox<>();
        jtCi = new javax.swing.JTextField();
        jtDireccion = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        fechaRegistro = new com.toedter.calendar.JDateChooser();

        menuTabla.setText("jMenu1");

        menuModificar.setText("Modificar");
        menuTabla.add(menuModificar);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel11.setText("Registro Cliente");

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 313, Short.MAX_VALUE))
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(PanelSuperior, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        jPanel6.add(bGuardar);

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        jPanel6.add(bEliminar);

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });
        jPanel6.add(bModificar);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        PanelImagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/user4.png"))); // NOI18N
        jImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImagenMouseClicked(evt);
            }
        });
        PanelImagen.add(jImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 6, 270, 260));

        jPanel1.add(PanelImagen, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        PanelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lNombre.setText("Nombre");
        PanelFormulario.add(lNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lApellido.setText("Apellido");
        PanelFormulario.add(lApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 60, 20));

        lsexo.setText("Sexo");
        PanelFormulario.add(lsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lDireccion.setText("Direccion");
        PanelFormulario.add(lDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        lci.setText("C. I.");
        PanelFormulario.add(lci, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lTelefono.setText("Telefono");
        PanelFormulario.add(lTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lFecha.setText("Fecha Registro");
        PanelFormulario.add(lFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 30));

        jtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNombreKeyTyped(evt);
            }
        });
        PanelFormulario.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 170, -1));

        jtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtApellidoKeyTyped(evt);
            }
        });
        PanelFormulario.add(jtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, -1));

        jCombSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        PanelFormulario.add(jCombSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, -1));

        jtCi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCiKeyTyped(evt);
            }
        });
        PanelFormulario.add(jtCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, -1));

        jtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDireccionKeyTyped(evt);
            }
        });
        PanelFormulario.add(jtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 130, -1));

        jtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtTelefonoKeyTyped(evt);
            }
        });
        PanelFormulario.add(jtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, -1));

        fechaRegistro.setDateFormatString("dd/MM/yyyy");
        PanelFormulario.add(fechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 130, -1));

        add(PanelFormulario, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImagenMouseClicked
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG", "PNG & GIF", "jpg", "png", "gif");
	jf.setFileFilter(fil);
	jf.setCurrentDirectory(new File("Fotos"));

	int estado = jf.showOpenDialog(null);

	if (estado == JFileChooser.APPROVE_OPTION) {

	Image icono;
	try {

                icono = ImageIO.read(jf.getSelectedFile()).getScaledInstance(jImagen.getWidth(),jImagen.getHeight(), Image.SCALE_DEFAULT);
                f = new byte[(int) (jf.getSelectedFile().length())];
                jImagen.setIcon(new ImageIcon(icono));
                jImagen.updateUI();
            } catch (IOException e1) {
                e1.printStackTrace();
            }
	}
    }//GEN-LAST:event_jImagenMouseClicked

    private void jtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreKeyTyped
        char c= evt.getKeyChar();    
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtNombreKeyTyped

    private void jtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApellidoKeyTyped
         char c= evt.getKeyChar();    
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtApellidoKeyTyped

    private void jtCiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCiKeyTyped
        char car = evt.getKeyChar();
        if(jtCi.getText().length()>=9) evt.consume();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_jtCiKeyTyped

    private void jtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDireccionKeyTyped
        char c= evt.getKeyChar();    
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c!=(char)KeyEvent.VK_SPACE)&&(c<'0' || c>'9'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtDireccionKeyTyped

    private void jtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelefonoKeyTyped
         char c= evt.getKeyChar();
        if(jtTelefono.getText().length()>=8) evt.consume();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_jtTelefonoKeyTyped

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
            
        if(validador()){
        String nom,ape,sex,ci,dir,tel,fecha;
            String sql="";
            nom=jtNombre.getText();
            ape=jtApellido.getText();
            sex=jCombSexo.getSelectedItem().toString();
            ci=jtCi.getText();
            dir=jtDireccion.getText();
            tel=jtTelefono.getText();
            fecha = fechaRegistro.getCalendar().get(Calendar.YEAR)+"-"+(fechaRegistro.getCalendar().get(Calendar.MONTH)+1)+"-"+fechaRegistro.getCalendar().get(Calendar.DAY_OF_MONTH);
            
            System.out.println(fecha);
           
            
            sql="INSERT INTO Cliente (ciCliente,nombreCliente,apellidoCliente,sexoCliente,direccionCliente,telefonoCliente,fechaRegCliente,fotoCliente) "
                    + "       VALUES (?,?,?,?,?,?,?)";
        try {
            PreparedStatement pst  = cn.prepareStatement(sql);
            pst.setString(1, ci);
            pst.setString(2, nom);
            pst.setString(3, ape);
            pst.setString(4, sex);
            pst.setString(5, dir);
            pst.setString(6, tel);
            pst.setString(7, fecha);
            pst.setBytes(8, f);
            
            
            int n=pst.executeUpdate();
            if(n>0){
            JOptionPane.showMessageDialog(null, "Registro Guardado con Exito");
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        Buscar b=new Buscar("Cliente");
        b.BuscarCliente();
        b.setVisible(true);
       
        
    }//GEN-LAST:event_bModificarActionPerformed

    public boolean validarNombre(){
        boolean res=false;
        Pattern patron = Pattern.compile("[a-zA-Z ]");
        Matcher m = patron.matcher(jtNombre.getText());
         if (m.find())
            res=true;
        
        return res;
    } 
    
    public boolean validarApellido(){
        boolean res=false;
        Pattern patron = Pattern.compile("[a-zA-Z ]");
        Matcher m = patron.matcher(jtApellido.getText());
         if (m.find())
            res=true;
        
        return res;
    } 
    
     public boolean validarTelefono(){
        boolean res=false;
        Pattern patron = Pattern.compile("^4[0-9]{6}$");
        Matcher m = patron.matcher(jtTelefono.getText());
         if (m.find()){
             res=true;
         }
         
        patron = Pattern.compile("^[7,6][0-9]{7}$");
        m = patron.matcher(jtTelefono.getText());
        
        if(m.find()){
             res=true;
         }
         
        
        return res;
    }
    public boolean validarCi(){
        boolean res=false;
        Pattern patron = Pattern.compile("[0-9]");
        Matcher m = patron.matcher(jtCi.getText());
        if (m.find()){
            res=true;
        }
                
        return res;
    }
    public boolean validador(){
        boolean res = true;
        if(validarNombre()&&!jtNombre.getText().equals("")){
            if(validarApellido()&&!jtApellido.getText().equals("")){
                if(validarCi()&&!jtCi.getText().equals("")){
                        if(!jtDireccion.getText().equals("")){
                                if(validarTelefono()&&!jtTelefono.getText().equals("")){
                                        
                                 }else{
                                    res=false;
                                    JOptionPane.showMessageDialog(null, "Verifique el Telefono");
                                    }
                        }else{
                            res=false;
                            JOptionPane.showMessageDialog(null, "Verifique el Direccion");
                        }
                 }else{
                    res=false;
                    JOptionPane.showMessageDialog(null, "Verifique el C.I.");
                }
            }else{
                res=false;
                JOptionPane.showMessageDialog(null, "Verifique el Apellido");
        
            }
        }else{
            res=false;
            JOptionPane.showMessageDialog(null, "Verifique el Nombre");
        }
        
        return res;
    }
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFormulario;
    private javax.swing.JPanel PanelImagen;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bModificar;
    private com.toedter.calendar.JDateChooser fechaRegistro;
    private javax.swing.JComboBox<String> jCombSexo;
    private javax.swing.JLabel jImagen;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCi;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTelefono;
    private javax.swing.JLabel lApellido;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JLabel lci;
    private javax.swing.JLabel lsexo;
    private javax.swing.JMenuItem menuModificar;
    private javax.swing.JMenu menuTabla;
    // End of variables declaration//GEN-END:variables
}
