/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;

import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Wilson
 */
public class RegistrarEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarEmpleado
     */
    public RegistrarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        bGuardar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelFormulario = new javax.swing.JPanel();
        lNombre = new javax.swing.JLabel();
        lApellido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lDireccion = new javax.swing.JLabel();
        lCi = new javax.swing.JLabel();
        lTelfono = new javax.swing.JLabel();
        lFechaIngreso = new javax.swing.JLabel();
        lFechaSalida = new javax.swing.JLabel();
        lSalario = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        jCombSexo = new javax.swing.JComboBox<>();
        tfCi = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfSalario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboTipoEmpleado = new javax.swing.JComboBox<>();
        jDateIngreso = new com.toedter.calendar.JDateChooser();
        jDateSalida = new com.toedter.calendar.JDateChooser();
        lCorreo = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel11.setText("Registro Empleado");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 257, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        jPanel6.add(bGuardar);

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        jPanel6.add(bEliminar);

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });
        jPanel6.add(bModificar);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/user4.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 6, 270, 260));

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        panelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lNombre.setText("Nombre");
        panelFormulario.add(lNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lApellido.setText("Apellido");
        panelFormulario.add(lApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel4.setText("Sexo");
        panelFormulario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        lDireccion.setText("Direccion");
        panelFormulario.add(lDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        lCi.setText("C. I.");
        panelFormulario.add(lCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lTelfono.setText("Telefono");
        panelFormulario.add(lTelfono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        lFechaIngreso.setText("Fecha Ingreso");
        panelFormulario.add(lFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        lFechaSalida.setText("Fecha Salida");
        panelFormulario.add(lFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lSalario.setText("Salario");
        panelFormulario.add(lSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreKeyTyped(evt);
            }
        });
        panelFormulario.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 170, -1));

        tfApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfApellidoKeyTyped(evt);
            }
        });
        panelFormulario.add(tfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, -1));

        jCombSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        panelFormulario.add(jCombSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 130, -1));

        tfCi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCiKeyTyped(evt);
            }
        });
        panelFormulario.add(tfCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, -1));

        tfDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDireccionKeyTyped(evt);
            }
        });
        panelFormulario.add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 130, -1));

        tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyTyped(evt);
            }
        });
        panelFormulario.add(tfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, -1));

        tfSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSalarioKeyTyped(evt);
            }
        });
        panelFormulario.add(tfSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 130, -1));

        jLabel12.setText("Tipo de Empleado");
        panelFormulario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 150, 20));

        jComboTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelFormulario.add(jComboTipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 120, -1));
        panelFormulario.add(jDateIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 130, -1));
        panelFormulario.add(jDateSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 130, -1));

        lCorreo.setText("Correo");
        panelFormulario.add(lCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        tfCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCorreoKeyTyped(evt);
            }
        });
        panelFormulario.add(tfCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 220, -1));

        add(panelFormulario, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyTyped
        char c= evt.getKeyChar();    
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c!=(char)KeyEvent.VK_SPACE))
          evt.consume();
        
    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidoKeyTyped
       char c= evt.getKeyChar();    
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c!=(char)KeyEvent.VK_SPACE))
          evt.consume();
    }//GEN-LAST:event_tfApellidoKeyTyped

    private void tfCiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCiKeyTyped
        char car = evt.getKeyChar();
        if(tfCi.getText().length()>=9) evt.consume();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_tfCiKeyTyped

    private void tfDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDireccionKeyTyped
        char c= evt.getKeyChar();    
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && (c!=(char)KeyEvent.VK_SPACE)&&(c<'0' || c>'9'))
          evt.consume();
    }//GEN-LAST:event_tfDireccionKeyTyped

    private void tfTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyTyped
        char c= evt.getKeyChar();
        if(tfTelefono.getText().length()>=8) evt.consume();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_tfTelefonoKeyTyped

    private void tfSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSalarioKeyTyped
         char c = evt.getKeyChar();
                if(((c < '0') || (c > '9'))   && (c !='.')){
                /* lo que deseo colocar aqui es si ya se pulso el caracter (.) el mismo no se pueda repetir*/
                    evt.consume();
                }
                if (c == '.' && tfSalario.getText().contains(".")) {
                    evt.consume();
                }
                
                
    }//GEN-LAST:event_tfSalarioKeyTyped

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        validador();
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bModificarActionPerformed

    private void tfCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCorreoKeyTyped

    
    public boolean validarNombre(){
        boolean res=false;
        Pattern patron = Pattern.compile("[a-zA-Z ]");
        Matcher m = patron.matcher(tfNombre.getText());
         if (m.find())
            res=true;
        
        return res;
    } 
    
    public boolean validarApellido(){
        boolean res=false;
        Pattern patron = Pattern.compile("[a-zA-Z ]");
        Matcher m = patron.matcher(tfApellido.getText());
         if (m.find())
            res=true;
        
        return res;
    } 
    
     public boolean validarTelefono(){
        boolean res=false;
        Pattern patron = Pattern.compile("^4[0-9]{6}$");
        Matcher m = patron.matcher(tfTelefono.getText());
         if (m.find()){
             res=true;
         }
         
        patron = Pattern.compile("^[7,6][0-9]{7}$");
        m = patron.matcher(tfTelefono.getText());
        
        if(m.find()){
             res=true;
         }
         
        
        return res;
    }
     public boolean validarCi(){
        boolean res=false;
        Pattern patron = Pattern.compile("[0-9]");
        Matcher m = patron.matcher(tfCi.getText());
        if (m.find()){
            res=true;
        }
                
        return res;
    }
     
    public boolean validarSalario(){
        boolean res=false;
        Pattern patron = Pattern.compile("^\\d+|^\\d+\\.?\\d+");
        Matcher m = patron.matcher(tfSalario.getText());
        if (m.find()){
            res=true;
        }
                
        return res;
    }
    
    public boolean validarCorreo(){
        boolean res=false;
        Pattern patron = Pattern.compile( "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher m = patron.matcher(tfCorreo.getText());
        if (m.find()){
            res=true;
        }
                
        return res;
    }
     
    public boolean validador(){
        boolean res = true;
        if(validarNombre()&&!tfNombre.getText().equals("")){
            if(validarApellido()&&!tfApellido.getText().equals("")){
                if(validarCi()&&!tfCi.getText().equals("")){
                        if(!tfDireccion.getText().equals("")){
                                if(validarTelefono()&&!tfTelefono.getText().equals("")){
                                        
                                    if(validarSalario() && !tfSalario.getText().equals("")){
                                        if(validarCorreo() && !tfCorreo.getText().equals("")){
            
                                        }else{
                                            res=false;
                                        JOptionPane.showMessageDialog(null, "Verifique el correo");
                                        }    
                                        
                                        
                                    }else{
                                        res=false;
                                        JOptionPane.showMessageDialog(null, "Verifique el Salario");
                                    }
                                    
                                   }else{
                                    res=false;
                                    JOptionPane.showMessageDialog(null, "Verifique el Telefono");
                                    }
                        }else{
                            res=false;
                            JOptionPane.showMessageDialog(null, "Verifique el Direccion");
                        }
                 }else{
                    res=false;
                    JOptionPane.showMessageDialog(null, "Verifique el C.I.");
                }
            }else{
                res=false;
                JOptionPane.showMessageDialog(null, "Verifique el Apellido");
        
            }
        }else{
            res=false;
            JOptionPane.showMessageDialog(null, "Verifique el Nombre");
        }
        
        return res;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bModificar;
    private javax.swing.JComboBox<String> jCombSexo;
    private javax.swing.JComboBox<String> jComboTipoEmpleado;
    private com.toedter.calendar.JDateChooser jDateIngreso;
    private com.toedter.calendar.JDateChooser jDateSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lApellido;
    private javax.swing.JLabel lCi;
    private javax.swing.JLabel lCorreo;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lFechaIngreso;
    private javax.swing.JLabel lFechaSalida;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lSalario;
    private javax.swing.JLabel lTelfono;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCi;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfSalario;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
